### ISSUE TITLE
(Mod Compatibility) Unearthed is incompatible

### ISSUE THREAD

**Issue by lerokko** [PersonTheCat/OreStoneVariants#128]
### Observerd behavoir:
The ores from Ore stone Variants have textures from (what i presume) was generated there before Unearthed replaced those  stones with its own materials. From what I understand Unearthed generates its stones at a very late stage to still let blacklisted stones generate normally.

### Mods used:
Using the latest version of Forge, Ore stone Variants, Unearthed, and Quark for 1,16,5.
Mod in qestion https://www.curseforge.com/minecraft/mc-mods/unearthed-forge

### Other info
**I added the ores to the unearthed materials via */osv put all ...* commands, they show up in the config and in JEI.**
I assume this is because unearthed changes all stone types underground very late during world generation (even after quark and Ore stone Variants). Is it possible to defer Ore stone Variants to an even later stage in world generation, similar to quark, so that it replaces the regular ores with variants after Unearthed replaced the underground stones with the stones from their mod.

From what i understand quark has nothing to do with it. Its just that even if Ore stone Variants does its thing after quark its still to early for Unearthed. Unearthed still comes after that.

**Comment by PersonTheCat** [comment]
I am aware of this issue and the problem is that unearthed deliberately coerces all stone blocks into its own as late as possible. This is their design choice and, as a result, these two mods are fundamentally incompatible. 

You should consider raising this issue with them and see if they're willing to change it. 

I'll leave this open for visibility in the meantime but there's nothing I can do.
