### ISSUE TITLE
Random JVM crash on client

### ISSUE THREAD

**Issue by frank89722** [PersonTheCat/OreStoneVariants#142]
Forge 36.2.22
Catlib 1.7
OSV 7.2
JRE 8.0_311

This happens randomly on joining a world but it always happened when the debug log shows
`[Render thread/DEBUG] [personthecat.osv.world.interceptor.InterceptorDispatcher/]: Creating client interceptor for type: class net.minecraft.client.world.ClientWorld in thread: Thread[Render thread,5,main]`

JVM crash log: [hs_err_pid22856.log](https://github.com/PersonTheCat/OreStoneVariants/files/7793347/hs_err_pid22856.log)
debug log: [debug.log](https://github.com/PersonTheCat/OreStoneVariants/files/7793352/debug.log)

**Comment by PersonTheCat** [comment]
Wow, this does look accurate. Unfortunately, though, I've run through this quite a few times and have never experienced this crash. Without a actual stack trace (or any meaningful frames in the memory dump), I don't think I can fix this. 

How many times has this happened and are you willing to run a debug build for me to provide some extra details next time it does?

**Comment by frank89722** [comment]
It's happened a lot in my mod pack (about 50% chance) and of course I'm happy to help

**Comment by PersonTheCat** [comment]
Great, thanks! You'll need to change the extension on this file to `.jar` in order to load it, of course. This build basically just includes a bunch of extra log statements since I'm not able to see anything here or reproduce the issue and debug it properly.

It's worth noting that I did change the behavior very slightly so I can get more details. It's possible that this change will fix the issue, although I doubt it. In any case, please give this a handful of tries and let me know if that works! If you can get it to crash, just share the same info as before.

[OSV-Forge-7.2.1-remapped.zip](https://github.com/PersonTheCat/OreStoneVariants/files/7793620/OSV-Forge-7.2.1-remapped.zip)

Thanks a lot for your help!

**Comment by frank89722** [comment]
I have tested it around 10 times and seems like 7.2.1 has fixed the issue but I'm not 100% sure.
I have planned to release my Curseforge modpack beta update tomorrow with OSV so if you could upload 7.2.1 to CF I'll pack it in my pack and test it with some beta testers to confirm it's actually fixed.

**Comment by PersonTheCat** [comment]
Sure. I do have another way to potentially atomize this operation. It's _possible_ there's a race condition, but it's extremely hard to say. In any case, I don't want to make that change yet in case it winds up breaking things. I'll upload that in a bit. Just update here whenever you can and we'll try to get this worked out if it happens, even once.

Thanks again for your time!

**Comment by PersonTheCat** [comment]
Just a quick update on this ticket: I have released the update for OSV 7.3. This build includes quite a few fixes on top of this one, so just know that any feedback you can provide at all will be extremely valuable.

Anyway, hoping for the best!

**Comment by frank89722** [comment]
Seems like this was fixed perfectly after OSV 7.3 at least it never happen to me after 7.3. And it has been tested by about 10 users on my server for 3 days and no one report any issues related to this one.

**Comment by PersonTheCat** [comment]
Hey, this is really great. Thanks for the update! Feel free to reopen this issue, if needed.
