### ISSUE TITLE
OSV cannot start without CatLib

### ISSUE THREAD

**Issue by FelipeCardona95** [PersonTheCat/OreStoneVariants#146]
Hey currenly Im getting my server failing to start this is what the crash report says, let me know if its not related or if you have any aditional info 
crash report:
https://pastebin.com/xnbXXgkj
using OSV 7.4
on mc 1.16.5
forge 36.2.22

**Comment by PersonTheCat** [comment]
You need CatLib to use this mod. Make sure you have that installed, try again, and report back with any changes.

**Comment by FelipeCardona95** [comment]
That made it thank you, this is from a modpack, I will report that to them

**Comment by FelipeCardona95** [comment]
On the client you dont need the CatLib?

**Comment by PersonTheCat** [comment]
No, CatLib is pretty much always required, client and server included since OSV 7.0.

**Comment by FelipeCardona95** [comment]
Hey so I tried again with 6.2 but getting this error on the client, is the same thing? or should I just update?
https://pastebin.com/s42Pyep8

**Comment by PersonTheCat** [comment]
I don't recommend downgrading. There were tons of major changes under the hood. Lots of that can be converted from 6.x to 7.x, but of course not the other way around. I also cannot support older versions of the mod. 

Was this mod pack made with 6.2? You may just need to get a fresh install of the mod pack, since OSV will update all of your configs and make them incompatible with that version.
