### ISSUE TITLE
[1.12.2] Resource Pack with OSV

### ISSUE THREAD

**Issue by reddvilzz** [PersonTheCat/OreStoneVariants#166]
Hi there, I'm on 1.12.2 and was wondering since I'm using some resource pack, is there anyway to make the ore stone variants to blend in with the different stone textures I'm using?

I'm using Modernity-format3-v3.7.0.zip and Vanilla_Future_Texture_optifine.zip for the resource pack.

![here is the example](https://user-images.githubusercontent.com/6846358/180044809-6a3bb744-cd62-476e-afc4-b237f034bdb9.png)

and here is my [config](https://github.com/PersonTheCat/OreStoneVariants/files/9152412/osv.log) if needed. (Had to change it to .log instead so it can be uploaded here.)

**Comment by PersonTheCat** [comment]
@reddvilzz In OSV 5.x, the models are loaded dynamically. The background layer is copied directly from the origin model at runtime, so it should already use that texture. Are you using any shaders? It looks like it might just be a lighting issue, which can happen with shaders since these blocks render in the translucent render layer.

**Comment by PersonTheCat** [comment]
@reddvilzz Thanks! Sounds like this is an Optifine behavior. Thanks for clarifying. I would typically leave this kind of issue open for visibility, but I don't anticipate other users running into the same kind of issue anytime soon, so I will be closing it. Please let me know if you encounter any other issues and we'll try to work em out.
