### ISSUE TITLE
[1.16, 1.18] Compatability Issue with Masterful Machinery

### ISSUE THREAD

**Issue by MundM2007** [PersonTheCat/OreStoneVariants#172]
when both OSV and MM is installed it crashes on startup, I have talked with the MM dev on discord and this is caused by your mod. They said to me the following regarding the 1.16 version: "theyre getting the list of resource packs before the mm has initialised which causes it to fail cause it failed tryna find what to generate". Logs are added below
1.16:
[latest.log](https://github.com/PersonTheCat/OreStoneVariants/files/11525074/latest.log)
1.18:
[latest.log](https://github.com/PersonTheCat/OreStoneVariants/files/11525075/latest.log)

**Comment by PersonTheCat** [comment]
Thanks, I'll investigate.

**Comment by PersonTheCat** [comment]
@MundM2007 I successfully reproduced the error and confirmed that it can be fixed by deferring the overlay model generation event. This may create glitches the first time you generate resources with OSV if you're using the overlay models, which are off by default. It also may not. :shrug: I think that's a worthwhile trade-off.

I'll update that and upload to CurseForge in just a sec.

**Comment by MundM2007** [comment]
Thanks for this quick fix!
