### ISSUE TITLE
Particles Wont Render In Front of Ores

### ISSUE THREAD

**Issue by Ecdragonz** [PersonTheCat/OreStoneVariants#71]
No idea why this happens. Bur Heres an image. Its not just the dirt ore, i added that myself. You can see it with the stone coal ore in behind it. It also happens with rain But im using potion particles as an example.
![2019-07-24_22 11 03](https://user-images.githubusercontent.com/45206350/61840776-4ccb5c00-ae60-11e9-835c-7be4c861af6b.png)

**Comment by PersonTheCat** [comment]
This is because of their render layer. The blocks are technically transparent for the overlays to render correctly. The same thing happens with other transparent blocks, like glass. There used to be a config setting for this, but I wound up removing it in a super early version of the mod. The problem is that some textures just don't look right without it. Sorry about that!
